# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\\PyCharmProjects\\Dicom_database\\ui\\search.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AppWindow(object):
    def setupUi(self, AppWindow):
        AppWindow.setObjectName(_fromUtf8("AppWindow"))
        AppWindow.resize(685, 740)
        AppWindow.setStyleSheet(_fromUtf8("#AppWindow {\n"
"    background-image: url(:/image/medical-background-with-loop_4p1uvboye__F0008.png);\n"
"}"))
        self.centralwidget = QtGui.QWidget(AppWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.result_table = QtGui.QTableView(self.centralwidget)
        self.result_table.setGeometry(QtCore.QRect(10, 340, 661, 381))
        self.result_table.setObjectName(_fromUtf8("result_table"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 661, 261))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.basicLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.basicLayout.setObjectName(_fromUtf8("basicLayout"))
        self.instituition_name_edit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.instituition_name_edit.setObjectName(_fromUtf8("instituition_name_edit"))
        self.basicLayout.addWidget(self.instituition_name_edit, 1, 7, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.basicLayout.addItem(spacerItem, 2, 4, 1, 2)
        self.patient_id_label = QtGui.QLabel(self.gridLayoutWidget)
        self.patient_id_label.setAlignment(QtCore.Qt.AlignCenter)
        self.patient_id_label.setObjectName(_fromUtf8("patient_id_label"))
        self.basicLayout.addWidget(self.patient_id_label, 1, 1, 1, 1)
        self.physician_edit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.physician_edit.setObjectName(_fromUtf8("physician_edit"))
        self.basicLayout.addWidget(self.physician_edit, 3, 3, 1, 1)
        self.instutuition_name_label = QtGui.QLabel(self.gridLayoutWidget)
        self.instutuition_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.instutuition_name_label.setObjectName(_fromUtf8("instutuition_name_label"))
        self.basicLayout.addWidget(self.instutuition_name_label, 1, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.basicLayout.addItem(spacerItem1, 3, 4, 1, 2)
        self.patient_gender_edit = QtGui.QLineEdit(self.gridLayoutWidget)
        self.patient_gender_edit.setObjectName(_fromUtf8("patient_gender_edit"))
        self.basicLayout.addWidget(self.patient_gender_edit, 1, 3, 1, 1)
        self.image_date_label = QtGui.QLabel(self.gridLayoutWidget)
        self.image_date_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_date_label.setObjectName(_fromUtf8("image_date_label"))
        self.basicLayout.addWidget(self.image_date_label, 3, 6, 1, 1)
        self.patient_gender_label = QtGui.QLabel(self.gridLayoutWidget)
        self.patient_gender_label.setAlignment(QtCore.Qt.AlignCenter)
        self.patient_gender_label.setObjectName(_fromUtf8("patient_gender_label"))
        self.basicLayout.addWidget(self.patient_gender_label, 2, 1, 1, 1)
        self.advanced_condition_edit = QtGui.QPlainTextEdit(self.gridLayoutWidget)
        self.advanced_condition_edit.setObjectName(_fromUtf8("advanced_condition_edit"))
        self.basicLayout.addWidget(self.advanced_condition_edit, 4, 3, 1, 5)
        self.physician_label = QtGui.QLabel(self.gridLayoutWidget)
        self.physician_label.setAlignment(QtCore.Qt.AlignCenter)
        self.physician_label.setObjectName(_fromUtf8("physician_label"))
        self.basicLayout.addWidget(self.physician_label, 3, 1, 1, 1)
        self.modality_label = QtGui.QLabel(self.gridLayoutWidget)
        self.modality_label.setAlignment(QtCore.Qt.AlignCenter)
        self.modality_label.setObjectName(_fromUtf8("modality_label"))
        self.basicLayout.addWidget(self.modality_label, 2, 6, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.basicLayout.addItem(spacerItem2, 1, 4, 1, 2)
        self.patientBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.patientBox.setObjectName(_fromUtf8("patientBox"))
        self.basicLayout.addWidget(self.patientBox, 0, 3, 1, 1)
        self.image_date_edit = QtGui.QDateEdit(self.gridLayoutWidget)
        self.image_date_edit.setObjectName(_fromUtf8("image_date_edit"))
        self.basicLayout.addWidget(self.image_date_edit, 3, 7, 1, 1)
        self.studyBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.studyBox.setObjectName(_fromUtf8("studyBox"))
        self.basicLayout.addWidget(self.studyBox, 0, 4, 1, 1)
        self.imageBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.imageBox.setObjectName(_fromUtf8("imageBox"))
        self.basicLayout.addWidget(self.imageBox, 0, 6, 1, 1)
        self.serieBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.serieBox.setObjectName(_fromUtf8("serieBox"))
        self.basicLayout.addWidget(self.serieBox, 0, 5, 1, 1)
        self.dicomBox = QtGui.QCheckBox(self.gridLayoutWidget)
        self.dicomBox.setObjectName(_fromUtf8("dicomBox"))
        self.basicLayout.addWidget(self.dicomBox, 0, 7, 1, 1)
        self.advanced_condition_label = QtGui.QLabel(self.gridLayoutWidget)
        self.advanced_condition_label.setAlignment(QtCore.Qt.AlignCenter)
        self.advanced_condition_label.setObjectName(_fromUtf8("advanced_condition_label"))
        self.basicLayout.addWidget(self.advanced_condition_label, 4, 1, 1, 1)
        self.model_label = QtGui.QLabel(self.gridLayoutWidget)
        self.model_label.setAlignment(QtCore.Qt.AlignCenter)
        self.model_label.setObjectName(_fromUtf8("model_label"))
        self.basicLayout.addWidget(self.model_label, 0, 1, 1, 1)
        self.modality_box = QtGui.QComboBox(self.gridLayoutWidget)
        self.modality_box.setObjectName(_fromUtf8("modality_box"))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.modality_box.addItem(_fromUtf8(""))
        self.basicLayout.addWidget(self.modality_box, 2, 7, 1, 1)
        self.patientGender_box = QtGui.QComboBox(self.gridLayoutWidget)
        self.patientGender_box.setObjectName(_fromUtf8("patientGender_box"))
        self.patientGender_box.addItem(_fromUtf8(""))
        self.patientGender_box.addItem(_fromUtf8(""))
        self.patientGender_box.addItem(_fromUtf8(""))
        self.basicLayout.addWidget(self.patientGender_box, 2, 3, 1, 1)
        self.search_button = QtGui.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(280, 300, 93, 28))
        self.search_button.setObjectName(_fromUtf8("search_button"))
        AppWindow.setCentralWidget(self.centralwidget)
        self.actionAdd_dicom = QtGui.QAction(AppWindow)
        self.actionAdd_dicom.setObjectName(_fromUtf8("actionAdd_dicom"))
        self.actionAdd_dicom_dir_DICOMDIR = QtGui.QAction(AppWindow)
        self.actionAdd_dicom_dir_DICOMDIR.setObjectName(_fromUtf8("actionAdd_dicom_dir_DICOMDIR"))
        self.actionCopy_dicom = QtGui.QAction(AppWindow)
        self.actionCopy_dicom.setObjectName(_fromUtf8("actionCopy_dicom"))
        self.actionDelete_dicom_file = QtGui.QAction(AppWindow)
        self.actionDelete_dicom_file.setObjectName(_fromUtf8("actionDelete_dicom_file"))
        self.actionQuery = QtGui.QAction(AppWindow)
        self.actionQuery.setObjectName(_fromUtf8("actionQuery"))
        self.actionAdvanced_query_For_Advanced_User = QtGui.QAction(AppWindow)
        self.actionAdvanced_query_For_Advanced_User.setObjectName(_fromUtf8("actionAdvanced_query_For_Advanced_User"))
        self.actionStorage = QtGui.QAction(AppWindow)
        self.actionStorage.setObjectName(_fromUtf8("actionStorage"))
        self.actionDicom_Image_Storage = QtGui.QAction(AppWindow)
        self.actionDicom_Image_Storage.setObjectName(_fromUtf8("actionDicom_Image_Storage"))

        self.retranslateUi(AppWindow)
        QtCore.QMetaObject.connectSlotsByName(AppWindow)

    def retranslateUi(self, AppWindow):
        AppWindow.setWindowTitle(_translate("AppWindow", "MainWindow", None))
        self.patient_id_label.setText(_translate("AppWindow", "Patient ID", None))
        self.instutuition_name_label.setText(_translate("AppWindow", "Instituition Name", None))
        self.image_date_label.setText(_translate("AppWindow", "Image Date", None))
        self.patient_gender_label.setText(_translate("AppWindow", "Patient Gender", None))
        self.physician_label.setText(_translate("AppWindow", "Physician", None))
        self.modality_label.setText(_translate("AppWindow", "Modality", None))
        self.patientBox.setText(_translate("AppWindow", "Patient", None))
        self.studyBox.setText(_translate("AppWindow", "Study", None))
        self.imageBox.setText(_translate("AppWindow", "Image", None))
        self.serieBox.setText(_translate("AppWindow", "Serie", None))
        self.dicomBox.setText(_translate("AppWindow", "DICOM", None))
        self.advanced_condition_label.setText(_translate("AppWindow", "Advanced\n"
"Condition\n"
" (MongoDB bson)", None))
        self.model_label.setText(_translate("AppWindow", "Model", None))
        self.modality_box.setItemText(0, _translate("AppWindow", "All", None))
        self.modality_box.setItemText(1, _translate("AppWindow", "CR", None))
        self.modality_box.setItemText(2, _translate("AppWindow", "MG", None))
        self.modality_box.setItemText(3, _translate("AppWindow", "PT", None))
        self.modality_box.setItemText(4, _translate("AppWindow", "XA", None))
        self.modality_box.setItemText(5, _translate("AppWindow", "ES", None))
        self.modality_box.setItemText(6, _translate("AppWindow", "CT", None))
        self.modality_box.setItemText(7, _translate("AppWindow", "MR", None))
        self.modality_box.setItemText(8, _translate("AppWindow", "RF", None))
        self.modality_box.setItemText(9, _translate("AppWindow", "US", None))
        self.modality_box.setItemText(10, _translate("AppWindow", "DX", None))
        self.modality_box.setItemText(11, _translate("AppWindow", "NM", None))
        self.modality_box.setItemText(12, _translate("AppWindow", "SC", None))
        self.modality_box.setItemText(13, _translate("AppWindow", "OT", None))
        self.patientGender_box.setItemText(0, _translate("AppWindow", "All", None))
        self.patientGender_box.setItemText(1, _translate("AppWindow", "M", None))
        self.patientGender_box.setItemText(2, _translate("AppWindow", "F", None))
        self.search_button.setText(_translate("AppWindow", "Search", None))
        self.actionAdd_dicom.setText(_translate("AppWindow", "Add dicom file (dcm)", None))
        self.actionAdd_dicom_dir_DICOMDIR.setText(_translate("AppWindow", "Add dicom dir (DICOMDIR)", None))
        self.actionCopy_dicom.setText(_translate("AppWindow", "Copy dicom", None))
        self.actionDelete_dicom_file.setText(_translate("AppWindow", "Delete dicom", None))
        self.actionQuery.setText(_translate("AppWindow", "Basic search", None))
        self.actionAdvanced_query_For_Advanced_User.setText(_translate("AppWindow", "Advanced query (For Advanced User)", None))
        self.actionStorage.setText(_translate("AppWindow", "URL Storage", None))
        self.actionDicom_Image_Storage.setText(_translate("AppWindow", "Dicom/Image Storage", None))

