# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\\PyCharmProjects\\Dicom_Database\\ui\\sign_up.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setFixedSize(488, 523)
        Form.setStyleSheet(_fromUtf8("#Form  {\n"
"    background-image: url(:/image/497102554.jpg);\n"
"}"))
        self.formLayoutWidget = QtGui.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 60, 441, 271))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setHorizontalSpacing(14)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.full_name_label = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.full_name_label.sizePolicy().hasHeightForWidth())
        self.full_name_label.setSizePolicy(sizePolicy)
        self.full_name_label.setMinimumSize(QtCore.QSize(100, 0))
        self.full_name_label.setStyleSheet(_fromUtf8("#full_name_label { color : white; }"))
        self.full_name_label.setObjectName(_fromUtf8("full_name_label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.full_name_label)
        self.full_name_edit = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.full_name_edit.sizePolicy().hasHeightForWidth())
        self.full_name_edit.setSizePolicy(sizePolicy)
        self.full_name_edit.setMinimumSize(QtCore.QSize(300, 20))
        self.full_name_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.full_name_edit.setObjectName(_fromUtf8("full_name_edit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.full_name_edit)
        self.username_label = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_label.sizePolicy().hasHeightForWidth())
        self.username_label.setSizePolicy(sizePolicy)
        self.username_label.setMinimumSize(QtCore.QSize(100, 0))
        self.username_label.setStyleSheet(_fromUtf8("#username_label { color : white; }"))
        self.username_label.setObjectName(_fromUtf8("username_label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.username_label)
        self.username_edit = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_edit.sizePolicy().hasHeightForWidth())
        self.username_edit.setSizePolicy(sizePolicy)
        self.username_edit.setMinimumSize(QtCore.QSize(300, 20))
        self.username_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.username_edit.setObjectName(_fromUtf8("username_edit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.username_edit)
        self.password_label = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_label.sizePolicy().hasHeightForWidth())
        self.password_label.setSizePolicy(sizePolicy)
        self.password_label.setMinimumSize(QtCore.QSize(100, 0))
        self.password_label.setStyleSheet(_fromUtf8("#password_label { color : white; }"))
        self.password_label.setObjectName(_fromUtf8("password_label"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.password_label)
        self.password_edit = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_edit.sizePolicy().hasHeightForWidth())
        self.password_edit.setSizePolicy(sizePolicy)
        self.password_edit.setMinimumSize(QtCore.QSize(300, 20))
        self.password_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.password_edit.setObjectName(_fromUtf8("password_edit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.password_edit)
        self.phone_label = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_label.sizePolicy().hasHeightForWidth())
        self.phone_label.setSizePolicy(sizePolicy)
        self.phone_label.setMinimumSize(QtCore.QSize(100, 0))
        self.phone_label.setStyleSheet(_fromUtf8("#phone_label { color : white; }"))
        self.phone_label.setObjectName(_fromUtf8("phone_label"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.phone_label)
        self.sign_in_button = QtGui.QPushButton(self.formLayoutWidget)
        self.sign_in_button.setStyleSheet(_fromUtf8("#sign_in_button{ background-color : darkBlue;color : white; }"))
        self.sign_in_button.setCheckable(False)
        self.sign_in_button.setChecked(False)
        self.sign_in_button.setObjectName(_fromUtf8("sign_in_button"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.sign_in_button)
        self.phone_edit = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_edit.sizePolicy().hasHeightForWidth())
        self.phone_edit.setSizePolicy(sizePolicy)
        self.phone_edit.setMinimumSize(QtCore.QSize(300, 20))
        self.phone_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.phone_edit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.phone_edit.setObjectName(_fromUtf8("phone_edit"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.phone_edit)
        self.formLayoutWidget_2 = QtGui.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 360, 441, 151))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setHorizontalSpacing(14)
        self.formLayout_2.setVerticalSpacing(20)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.info_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.info_label.setEnabled(True)
        self.info_label.setStyleSheet(_fromUtf8("#info_label { color : white; }"))
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName(_fromUtf8("info_label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.info_label)
        self.otp_password_label = QtGui.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otp_password_label.sizePolicy().hasHeightForWidth())
        self.otp_password_label.setSizePolicy(sizePolicy)
        self.otp_password_label.setMinimumSize(QtCore.QSize(200, 0))
        self.otp_password_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.otp_password_label.setStyleSheet(_fromUtf8("#otp_password_label { color : white; }"))
        self.otp_password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.otp_password_label.setObjectName(_fromUtf8("otp_password_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.otp_password_label)
        self.phone_edit_2 = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.phone_edit_2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_edit_2.sizePolicy().hasHeightForWidth())
        self.phone_edit_2.setSizePolicy(sizePolicy)
        self.phone_edit_2.setMinimumSize(QtCore.QSize(200, 20))
        self.phone_edit_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.phone_edit_2.setMouseTracking(True)
        self.phone_edit_2.setFrame(True)
        self.phone_edit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.phone_edit_2.setDragEnabled(False)
        self.phone_edit_2.setReadOnly(False)
        self.phone_edit_2.setObjectName(_fromUtf8("phone_edit_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.phone_edit_2)
        self.confirm_button = QtGui.QPushButton(self.formLayoutWidget_2)
        self.confirm_button.setEnabled(False)
        self.confirm_button.setStyleSheet(_fromUtf8("#confirm_button{ background-color : darkBlue;color : white; }"))
        self.confirm_button.setCheckable(False)
        self.confirm_button.setChecked(False)
        self.confirm_button.setObjectName(_fromUtf8("confirm_button"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.SpanningRole, self.confirm_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.full_name_label.setText(_translate("Form", "Full Name", None))
        self.full_name_edit.setToolTip(_translate("Form", "<html><head/><body><p>Should be in format: <span style=\" font-weight:600;\">&quot;Surname^Name&quot;</span></p></body></html>", None))
        self.username_label.setText(_translate("Form", "Username", None))
        self.password_label.setText(_translate("Form", "Password", None))
        self.phone_label.setText(_translate("Form", "Phone", None))
        self.sign_in_button.setText(_translate("Form", "Create account", None))
        self.phone_edit.setToolTip(_translate("Form", "<html><head/><body><p>Shoule be in format: <span style=\" font-weight:600;\">&quot;7(***)-**-**-**&quot;</span></p></body></html>", None))
        self.phone_edit.setInputMask(_translate("Form", "7(999)-999-99-99; ", None))
        self.info_label.setText(_translate("Form", "To confirm your account enter a password, which sent your phone", None))
        self.otp_password_label.setText(_translate("Form", "OTP password", None))
        self.confirm_button.setText(_translate("Form", "Confirm", None))

import window.resources
