# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\\PyCharmProjects\\Dicom_Database\\ui\\forgot_password.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(486, 525)
        Form.setStyleSheet(_fromUtf8("#Form  {\n"
                                     "    background-image: url(:/image/497102554.jpg);\n"
                                     "}"))
        self.formLayoutWidget_2 = QtGui.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 451, 194))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setHorizontalSpacing(14)
        self.formLayout_2.setVerticalSpacing(20)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.info_label = QtGui.QLabel(self.formLayoutWidget_2)
        self.info_label.setEnabled(True)
        self.info_label.setStyleSheet(_fromUtf8("#info_label { color : white; }"))
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName(_fromUtf8("info_label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.SpanningRole, self.info_label)
        self.otp_password_label = QtGui.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otp_password_label.sizePolicy().hasHeightForWidth())
        self.otp_password_label.setSizePolicy(sizePolicy)
        self.otp_password_label.setMinimumSize(QtCore.QSize(200, 0))
        self.otp_password_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.otp_password_label.setStyleSheet(_fromUtf8("#otp_password_label { color : white; }"))
        self.otp_password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.otp_password_label.setObjectName(_fromUtf8("otp_password_label"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.otp_password_label)
        self.otp_password_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.otp_password_edit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.otp_password_edit.sizePolicy().hasHeightForWidth())
        self.otp_password_edit.setSizePolicy(sizePolicy)
        self.otp_password_edit.setMinimumSize(QtCore.QSize(200, 20))
        self.otp_password_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.otp_password_edit.setMouseTracking(True)
        self.otp_password_edit.setFrame(True)
        self.otp_password_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.otp_password_edit.setDragEnabled(False)
        self.otp_password_edit.setReadOnly(False)
        self.otp_password_edit.setObjectName(_fromUtf8("otp_password_edit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.otp_password_edit)
        self.username_label = QtGui.QLabel(self.formLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_label.sizePolicy().hasHeightForWidth())
        self.username_label.setSizePolicy(sizePolicy)
        self.username_label.setMinimumSize(QtCore.QSize(200, 0))
        self.username_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.username_label.setStyleSheet(_fromUtf8("#username_label { color : white; }"))
        self.username_label.setAlignment(QtCore.Qt.AlignCenter)
        self.username_label.setObjectName(_fromUtf8("username_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.username_label)
        self.username_edit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.username_edit.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_edit.sizePolicy().hasHeightForWidth())
        self.username_edit.setSizePolicy(sizePolicy)
        self.username_edit.setMinimumSize(QtCore.QSize(200, 20))
        self.username_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.username_edit.setMouseTracking(True)
        self.username_edit.setInputMask(_fromUtf8(""))
        self.username_edit.setFrame(True)
        self.username_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.username_edit.setDragEnabled(False)
        self.username_edit.setReadOnly(False)
        self.username_edit.setObjectName(_fromUtf8("username_edit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.username_edit)
        self.confirm_button = QtGui.QPushButton(self.formLayoutWidget_2)
        self.confirm_button.setEnabled(False)
        self.confirm_button.setStyleSheet(_fromUtf8("#confirm_button{ background-color : darkBlue;color : white; }"))
        self.confirm_button.setCheckable(False)
        self.confirm_button.setChecked(False)
        self.confirm_button.setObjectName(_fromUtf8("confirm_button"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.confirm_button)
        self.otp_button = QtGui.QPushButton(self.formLayoutWidget_2)
        self.otp_button.setEnabled(True)
        self.otp_button.setMinimumSize(QtCore.QSize(200, 0))
        self.otp_button.setStyleSheet(_fromUtf8("#otp_button{ background-color : darkBlue;color : white; }"))
        self.otp_button.setCheckable(False)
        self.otp_button.setChecked(False)
        self.otp_button.setObjectName(_fromUtf8("otp_button"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.otp_button)
        self.formLayoutWidget_3 = QtGui.QWidget(Form)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(20, 280, 451, 194))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setHorizontalSpacing(14)
        self.formLayout_3.setVerticalSpacing(20)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.new_password_label = QtGui.QLabel(self.formLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_password_label.sizePolicy().hasHeightForWidth())
        self.new_password_label.setSizePolicy(sizePolicy)
        self.new_password_label.setMinimumSize(QtCore.QSize(200, 0))
        self.new_password_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.new_password_label.setStyleSheet(_fromUtf8("#new_password_label { color : white; }"))
        self.new_password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.new_password_label.setObjectName(_fromUtf8("new_password_label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.new_password_label)
        self.new_password_edit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.new_password_edit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_password_edit.sizePolicy().hasHeightForWidth())
        self.new_password_edit.setSizePolicy(sizePolicy)
        self.new_password_edit.setMinimumSize(QtCore.QSize(200, 20))
        self.new_password_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.new_password_edit.setMouseTracking(True)
        self.new_password_edit.setInputMask(_fromUtf8(""))
        self.new_password_edit.setFrame(True)
        self.new_password_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.new_password_edit.setDragEnabled(False)
        self.new_password_edit.setReadOnly(False)
        self.new_password_edit.setObjectName(_fromUtf8("new_password_edit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.new_password_edit)
        self.repeat_new_password_label = QtGui.QLabel(self.formLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repeat_new_password_label.sizePolicy().hasHeightForWidth())
        self.repeat_new_password_label.setSizePolicy(sizePolicy)
        self.repeat_new_password_label.setMinimumSize(QtCore.QSize(200, 0))
        self.repeat_new_password_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.repeat_new_password_label.setStyleSheet(_fromUtf8("#repeat_new_password_label { color : white; }"))
        self.repeat_new_password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.repeat_new_password_label.setObjectName(_fromUtf8("repeat_new_password_label"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.repeat_new_password_label)
        self.repeat_new_password_edit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.repeat_new_password_edit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repeat_new_password_edit.sizePolicy().hasHeightForWidth())
        self.repeat_new_password_edit.setSizePolicy(sizePolicy)
        self.repeat_new_password_edit.setMinimumSize(QtCore.QSize(200, 20))
        self.repeat_new_password_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.repeat_new_password_edit.setMouseTracking(True)
        self.repeat_new_password_edit.setFrame(True)
        self.repeat_new_password_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.repeat_new_password_edit.setDragEnabled(False)
        self.repeat_new_password_edit.setReadOnly(False)
        self.repeat_new_password_edit.setObjectName(_fromUtf8("repeat_new_password_edit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.repeat_new_password_edit)
        self.change_button = QtGui.QPushButton(self.formLayoutWidget_3)
        self.change_button.setEnabled(False)
        self.change_button.setStyleSheet(_fromUtf8("#change_button { background-color : darkBlue;color : white; }"))
        self.change_button.setCheckable(False)
        self.change_button.setChecked(False)
        self.change_button.setObjectName(_fromUtf8("change_button"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.SpanningRole, self.change_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.info_label.setText(_translate("Form", "To restore a password, enter a username", None))
        self.otp_password_label.setText(_translate("Form", "OTP password", None))
        self.username_label.setText(_translate("Form", "Username", None))
        self.confirm_button.setText(_translate("Form", "Confirm", None))
        self.otp_button.setText(_translate("Form", "Get OTP", None))
        self.new_password_label.setText(_translate("Form", "New password", None))
        self.repeat_new_password_label.setText(_translate("Form", "Repeat new password", None))
        self.change_button.setText(_translate("Form", "Change", None))

