# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\\PyCharmProjects\\Dicom_database\\ui\\main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class ImageView(QtGui.QGraphicsView):
  def __init__(self, parent=None,pixmap=None):
    super(ImageView, self).__init__(parent)
    self.pixmap = pixmap

class Ui_AppWindow(object):
    def setupUi(self, AppWindow):
        AppWindow.setObjectName(_fromUtf8("AppWindow"))
        AppWindow.setFixedSize(952, 740)
        AppWindow.setStyleSheet(_fromUtf8("#AppWindow {\n"
"    background-image: url(:/image/medical-background-with-loop_4p1uvboye__F0008.png);\n"
"}"))
        self.centralwidget = QtGui.QWidget(AppWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 30, 911, 661))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Patient = QtGui.QWidget()
        self.Patient.setObjectName(_fromUtf8("Patient"))
        self.patientTable = QtGui.QTableView(self.Patient)
        self.patientTable.setGeometry(QtCore.QRect(0, 0, 911, 631))
        self.patientTable.setObjectName(_fromUtf8("patientTable"))
        self.tabWidget.addTab(self.Patient, _fromUtf8(""))
        self.Study = QtGui.QWidget()
        self.Study.setObjectName(_fromUtf8("Study"))
        self.studyTable = QtGui.QTableView(self.Study)
        self.studyTable.setGeometry(QtCore.QRect(0, 0, 911, 641))
        self.studyTable.setObjectName(_fromUtf8("studyTable"))
        self.tabWidget.addTab(self.Study, _fromUtf8(""))
        self.Serie = QtGui.QWidget()
        self.Serie.setObjectName(_fromUtf8("Serie"))
        self.serieTable = QtGui.QTableView(self.Serie)
        self.serieTable.setGeometry(QtCore.QRect(0, 0, 911, 641))
        self.serieTable.setObjectName(_fromUtf8("serieTable"))
        self.tabWidget.addTab(self.Serie, _fromUtf8(""))
        self.ImageInfo = QtGui.QWidget()
        self.ImageInfo.setObjectName(_fromUtf8("ImageInfo"))
        self.imageTable = QtGui.QTableView(self.ImageInfo)
        self.imageTable.setGeometry(QtCore.QRect(0, 0, 911, 631))
        self.imageTable.setObjectName(_fromUtf8("imageTable"))
        self.tabWidget.addTab(self.ImageInfo, _fromUtf8(""))
        self.ImageEdit = QtGui.QWidget()
        self.ImageEdit.setObjectName(_fromUtf8("ImageEdit"))
        self.imageTable2 = QtGui.QTableView(self.ImageEdit)
        self.imageTable2.setGeometry(QtCore.QRect(0, 10, 411, 561))
        self.imageTable2.setObjectName(_fromUtf8("imageTable2"))
        self.graphicsView = Label(self.ImageEdit)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setGeometry(QtCore.QRect(430, 70, 451, 461))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.gridLayoutWidget = QtGui.QWidget(self.ImageEdit)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(430, 20, 207, 41))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.point_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.point_button.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/icons8-pencil-drawing.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.point_button.setIcon(icon)
        self.point_button.setObjectName(_fromUtf8("point_button"))
        self.gridLayout.addWidget(self.point_button, 0, 0, 1, 1)
        self.polygon_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.polygon_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/icons8-polygon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polygon_button.setIcon(icon1)
        self.polygon_button.setObjectName(_fromUtf8("polygon_button"))
        self.gridLayout.addWidget(self.polygon_button, 0, 3, 1, 1)
        self.polyline_button = QtGui.QPushButton(self.gridLayoutWidget)
        self.polyline_button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/icons8-polyline.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polyline_button.setIcon(icon2)
        self.polyline_button.setObjectName(_fromUtf8("polyline_button"))
        self.gridLayout.addWidget(self.polyline_button, 0, 2, 1, 1)
        self.line_button = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_button.sizePolicy().hasHeightForWidth())
        self.line_button.setSizePolicy(sizePolicy)
        self.line_button.setMinimumSize(QtCore.QSize(0, 0))
        self.line_button.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/icons8-line.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.line_button.setIcon(icon3)
        self.line_button.setObjectName(_fromUtf8("line_button"))
        self.gridLayout.addWidget(self.line_button, 0, 1, 1, 1)
        self.gridLayoutWidget_3 = QtGui.QWidget(self.ImageEdit)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(530, 540, 207, 41))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.undo_button = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.undo_button.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/icons8-undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undo_button.setIcon(icon4)
        self.undo_button.setObjectName(_fromUtf8("undo_button"))
        self.gridLayout_3.addWidget(self.undo_button, 0, 0, 1, 1)
        self.save_button = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.save_button.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/icons8-add-image.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button.setIcon(icon5)
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.gridLayout_3.addWidget(self.save_button, 0, 1, 1, 1)
        self.redo_button = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.redo_button.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/image/icons8-redo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redo_button.setIcon(icon6)
        self.redo_button.setObjectName(_fromUtf8("redo_button"))
        self.gridLayout_3.addWidget(self.redo_button, 0, 2, 1, 1)
        self.tabWidget.addTab(self.ImageEdit, _fromUtf8(""))
        self.Dicom = QtGui.QWidget()
        self.Dicom.setObjectName(_fromUtf8("Dicom"))
        self.dicomTable = QtGui.QTableView(self.Dicom)
        self.dicomTable.setGeometry(QtCore.QRect(0, 0, 911, 641))
        self.dicomTable.setObjectName(_fromUtf8("dicomTable"))
        self.tabWidget.addTab(self.Dicom, _fromUtf8(""))
        AppWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(AppWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSearch = QtGui.QMenu(self.menubar)
        self.menuSearch.setObjectName(_fromUtf8("menuSearch"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        AppWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(AppWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        AppWindow.setStatusBar(self.statusbar)
        self.actionAdd_dicom = QtGui.QAction(AppWindow)
        self.actionAdd_dicom.setObjectName(_fromUtf8("actionAdd_dicom"))
        self.actionAdd_dicom_dir_DICOMDIR = QtGui.QAction(AppWindow)
        self.actionAdd_dicom_dir_DICOMDIR.setObjectName(_fromUtf8("actionAdd_dicom_dir_DICOMDIR"))
        self.actionDelete_dicom_file = QtGui.QAction(AppWindow)
        self.actionDelete_dicom_file.setObjectName(_fromUtf8("actionDelete_dicom_file"))
        self.actionQuery = QtGui.QAction(AppWindow)
        self.actionQuery.setObjectName(_fromUtf8("actionQuery"))
        self.actionQuery_For_Advanced_User = QtGui.QAction(AppWindow)
        self.actionQuery_For_Advanced_User.setObjectName(_fromUtf8("actionAdvanced_query_For_Advanced_User"))
        self.actionStorage = QtGui.QAction(AppWindow)
        self.actionStorage.setObjectName(_fromUtf8("actionStorage"))
        self.actionImage_Storage = QtGui.QAction(AppWindow)
        self.actionImage_Storage.setObjectName(_fromUtf8("actionImage_Storage"))
        self.actionAbout_app = QtGui.QAction(AppWindow)
        self.actionAbout_app.setObjectName(_fromUtf8("actionAbout_app"))
        self.menuFile.addAction(self.actionAdd_dicom)
        self.menuFile.addAction(self.actionAdd_dicom_dir_DICOMDIR)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionDelete_dicom_file)
        self.menuSearch.addAction(self.actionQuery)
        self.menuSearch.addAction(self.actionQuery_For_Advanced_User)
        self.menuSettings.addAction(self.actionStorage)
        self.menuSettings.addAction(self.actionImage_Storage)
        self.menuAbout.addAction(self.actionAbout_app)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSearch.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(AppWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AppWindow)

    def retranslateUi(self, AppWindow):
        AppWindow.setWindowTitle(_translate("AppWindow", "MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Patient), _translate("AppWindow", "Patient", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Study), _translate("AppWindow", "Study", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Serie), _translate("AppWindow", "Serie", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ImageInfo), _translate("AppWindow", "ImageInfo", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ImageEdit), _translate("AppWindow", "ImageEdit", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Dicom), _translate("AppWindow", "Dicom", None))
        self.menuFile.setTitle(_translate("AppWindow", "Edit", None))
        self.menuSearch.setTitle(_translate("AppWindow", "Search", None))
        self.menuSettings.setTitle(_translate("AppWindow", "Settings", None))
        self.menuAbout.setTitle(_translate("AppWindow", "About", None))
        self.actionAdd_dicom.setText(_translate("AppWindow", "Add dicom file (dcm)", None))
        self.actionAdd_dicom_dir_DICOMDIR.setText(_translate("AppWindow", "Add dicom dir (DICOMDIR)", None))
        self.actionDelete_dicom_file.setText(_translate("AppWindow", "Delete dicom", None))
        self.actionQuery.setText(_translate("AppWindow", "Basic search", None))
        self.actionQuery_For_Advanced_User.setText(_translate("AppWindow", "Advanced query (For Advanced User)", None))
        self.actionStorage.setText(_translate("AppWindow", "URL Storage", None))
        self.actionImage_Storage.setText(_translate("AppWindow", "Image Storage", None))
        self.actionAbout_app.setText(_translate("AppWindow","About app",None))


class Label(QtGui.QLabel):
    def __init__(self, parent=None):
        super(Label, self).__init__(parent=parent)

    def paintEvent(self, e):
        super().paintEvent(e)

